 export const weatherImages = {
    "Sunny": "https://wallpapercave.com/wp/wp4555644.jpg",
    "Partly cloudy": "http://2.bp.blogspot.com/-EUf8RMYHbcQ/TsO_E6dELLI/AAAAAAAAB7g/gnawt5AzyAA/s1600/DSC_1676.JPG",
    "Cloudy": "https://example.com/cloudy.jpg",
    "Overcast": "https://example.com/overcast.jpg",
    "Mist": "https://wallpaperaccess.com/full/2629855.jpg",
    "Patchy rain possible": "https://example.com/patchy-rain.jpg",
    "Patchy snow possible": "https://example.com/patchy-snow.jpg",
    "Patchy sleet possible": "https://example.com/patchy-sleet.jpg",
    "Patchy freezing drizzle possible": "https://example.com/patchy-freezing-drizzle.jpg",
    "Thundery outbreaks possible": "https://example.com/thundery-outbreaks.jpg",
    "Blowing snow": "https://example.com/blowing-snow.jpg",
    "Blizzard": "https://example.com/blizzard.jpg",
    "Fog": "https://example.com/fog.jpg",
    "Freezing fog": "https://example.com/freezing-fog.jpg",
    "Patchy light drizzle": "https://example.com/patchy-light-drizzle.jpg",
    "Light drizzle": "https://example.com/light-drizzle.jpg",
    "Freezing drizzle": "https://example.com/freezing-drizzle.jpg",
    "Heavy freezing drizzle": "https://example.com/heavy-freezing-drizzle.jpg",
    "Patchy light rain": "https://example.com/patchy-light-rain.jpg",
    "Light rain": "https://example.com/light-rain.jpg",
    "Moderate rain at times": "https://example.com/moderate-rain.jpg",
    "Moderate rain": "https://example.com/moderate-rain.jpg",
    "Heavy rain at times": "https://example.com/heavy-rain.jpg",
    "Heavy rain": "https://example.com/heavy-rain.jpg",
    "Light freezing rain": "https://example.com/light-freezing-rain.jpg",
    "Moderate or heavy freezing rain": "https://example.com/moderate-heavy-freezing-rain.jpg",
    "Light sleet": "https://example.com/light-sleet.jpg",
    "Moderate or heavy sleet": "https://example.com/moderate-heavy-sleet.jpg",
    "Patchy light snow": "https://example.com/patchy-light-snow.jpg",
    "Light snow": "https://example.com/light-snow.jpg",
    "Patchy moderate snow": "https://example.com/patchy-moderate-snow.jpg",
    "Moderate snow": "https://example.com/moderate-snow.jpg",
    "Patchy heavy snow": "https://example.com/patchy-heavy-snow.jpg",
    "Heavy snow": "https://example.com/heavy-snow.jpg",
    "Ice pellets": "https://example.com/ice-pellets.jpg",
    "Light rain shower": "https://example.com/light-rain-shower.jpg",
    "Moderate or heavy rain shower": "https://example.com/moderate-heavy-rain-shower.jpg",
    "Torrential rain shower": "https://example.com/torrential-rain-shower.jpg",
    "Light sleet showers": "https://example.com/light-sleet-showers.jpg",
    "Moderate or heavy sleet showers": "https://example.com/moderate-heavy-sleet-showers.jpg",
    "Light snow showers": "https://example.com/light-snow-showers.jpg",
    "Moderate or heavy snow showers": "https://example.com/moderate-heavy-snow-showers.jpg",
    "Light showers of ice pellets": "https://example.com/light-showers-ice-pellets.jpg",
    "Moderate or heavy showers of ice pellets": "https://example.com/moderate-heavy-showers-ice-pellets.jpg",
    "Patchy light rain with thunder": "https://example.com/patchy-light-rain-thunder.jpg",
    "Moderate or heavy rain with thunder": "https://example.com/moderate-heavy-rain-thunder.jpg",
    "Patchy light snow with thunder": "https://example.com/patchy-light-snow-thunder.jpg",
    "Moderate or heavy snow with thunder": "https://example.com/moderate-heavy-snow-thunder.jpg",
  };
  