 export const weatherImages = {
    "Sunny": "https://getwallpapers.com/wallpaper/full/8/4/d/924696-large-sunny-day-background-1920x1080-for-4k-monitor.jpg",
    "Partly cloudy":"https://wallpaperaccess.com/full/3397089.jpg ",
    "Patchy rain nearby":"https://www.vmcdn.ca/f/files/via/images/weather/rain-umbrella-vancouver-weather.jpg;w=960",
    "Clear":"https://s7d2.scene7.com/is/image/TWCNews/img_3214_jpg-2",
    "Overcast": "http://upload.wikimedia.org/wikipedia/commons/a/a3/Overcast_skies_from_Tropical_Storm_Danny.jpg",
    "Cloudy": "https://cdn.wallpapersafari.com/4/53/JCZUF5.jpg",
    "Mist": "https://wallpaperaccess.com/full/2629855.jpg",
    "Patchy rain possible": "https://wallpapercave.com/wp/wp6536561.jpg",
    "Patchy snow possible": "http://getwallpapers.com/wallpaper/full/3/f/2/1037119-most-popular-snowy-desktop-backgrounds-2708x1643.jpg",
    "Patchy sleet possible": "https://wallpapercave.com/wp/wp10190857.jpg",
    "Patchy freezing drizzle possible": "https://tse2.mm.bing.net/th?id=OIP.KX6xf7fJldK7dcoJ4yrSKgHaEK&pid=Api&P=0&h=180",
    "Thundery outbreaks possible": "https://wallpapercave.com/wp/wp9294651.jpg",
    "Blowing snow": "https://getwallpapers.com/wallpaper/full/5/d/2/411853.jpg",
    "Blizzard": "http://getwallpapers.com/wallpaper/full/8/8/8/1467112-snow-blizzard-wallpaper-1920x1080-for-android.jpg",
    "Fog": "https://wallpaperaccess.com/full/464474.jpg",
    "Freezing fog": "https://i.pinimg.com/originals/f2/b3/0d/f2b30db3c8bc87486f5b452dd6e6d300.jpg",
    "Patchy light drizzle": "https://c.wallhere.com/photos/39/38/rain_bokeh_water_drops_umbrella_glass-2025833.jpg!d",
    "Light drizzle": "https://wallpapercave.com/wp/wp8260484.jpg",
    "Freezing drizzle": "https://wallpapercave.com/wp/wp8260484.jpg",
    "Heavy freezing drizzle": "https://tse3.mm.bing.net/th?id=OIP.AV7hHB1po78rB3ukHPPBzgHaEK&pid=Api&P=0&h=180",
    "Patchy light rain": "https://example.com/patchy-light-rain.jpg",
    "Light rain": "https://example.com/light-rain.jpg",
    "Moderate rain at times": "https://example.com/moderate-rain.jpg",
    "Moderate rain": "https://example.com/moderate-rain.jpg",
    "Heavy rain at times": "https://example.com/heavy-rain.jpg",
    "Heavy rain": "https://example.com/heavy-rain.jpg",
    "Light freezing rain": "https://example.com/light-freezing-rain.jpg",
    "Moderate or heavy freezing rain": "https://example.com/moderate-heavy-freezing-rain.jpg",
    "Light sleet": "https://example.com/light-sleet.jpg",
    "Moderate or heavy sleet": "https://example.com/moderate-heavy-sleet.jpg",
    "Patchy light snow": "https://example.com/patchy-light-snow.jpg",
    "Light snow": "https://example.com/light-snow.jpg",
    "Patchy moderate snow": "https://example.com/patchy-moderate-snow.jpg",
    "Moderate snow": "https://example.com/moderate-snow.jpg",
    "Patchy heavy snow": "https://example.com/patchy-heavy-snow.jpg",
    "Heavy snow": "https://example.com/heavy-snow.jpg",
    "Ice pellets": "https://example.com/ice-pellets.jpg",
    "Light rain shower": "https://example.com/light-rain-shower.jpg",
    "Moderate or heavy rain shower": "https://example.com/moderate-heavy-rain-shower.jpg",
    "Torrential rain shower": "https://example.com/torrential-rain-shower.jpg",
    "Light sleet showers": "https://example.com/light-sleet-showers.jpg",
    "Moderate or heavy sleet showers": "https://example.com/moderate-heavy-sleet-showers.jpg",
    "Light snow showers": "https://example.com/light-snow-showers.jpg",
    "Moderate or heavy snow showers": "https://example.com/moderate-heavy-snow-showers.jpg",
    "Light showers of ice pellets": "https://example.com/light-showers-ice-pellets.jpg",
    "Moderate or heavy showers of ice pellets": "https://example.com/moderate-heavy-showers-ice-pellets.jpg",
    "Patchy light rain with thunder": "https://example.com/patchy-light-rain-thunder.jpg",
    "Moderate or heavy rain with thunder": "https://example.com/moderate-heavy-rain-thunder.jpg",
    "Patchy light snow with thunder": "https://example.com/patchy-light-snow-thunder.jpg",
    "Moderate or heavy snow with thunder": "https://example.com/moderate-heavy-snow-thunder.jpg",
  };
  